export const ActionType = {
  SELECT_LANGUAGE: "select_language",
  UPDATE_LINK: "update_link",
  UPDATE_NODE: "update_node",
  SHOW_UPDATE_MODAL: "show_update_modal",
  LOAD_SANKEY_DATA: "load_sankey_data",
  LOAD_SANKEY_SUCCESS: "load_sankey_success",
  LOAD_SANKEY_ERROR: "load_sankey_error",
  SET_ACTIVE_ITEM: "set_active_item",
  UNSET_ACTIVE_ITEM: "unset_active_item",
  UPDATE_LINK_AND_CLOSE_MODAL: "update_link_and_close_modal",
  UPDATE_NODE_AND_CLOSE_MODAL: "update_node_and_close_modal",
  UPDATE_ACTIVE_ITEM_VALUE: "update_active_item_value",
  ADD_NODE: "add_node",
  ADD_LINK: "add_link",
  CHANGE_LANGUAGE: "change_language",
};
